import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import React from "react";

interface SanctuaryAlertEmailProps {
  name: string;
  type: "BUDGET_ALERT" | "GOAL_REACHED" | "RECURRING_DEDUCTED" | "LIMIT_WARNING";
  title: string;
  message: string;
  actionUrl: string;
}

export function SanctuaryAlertEmail({
  name = "Sanctuary Owner",
  type = "BUDGET_ALERT",
  title = "Important Alert",
  message = "An event has occurred within your financial sanctuary.",
  actionUrl = "http://localhost:3000/dashboard",
}: SanctuaryAlertEmailProps) {
  
  // Dynamic styling based on alert type
  let accentColor = "#005147"; // Default Emerald
  let icon = "🔔";

  switch (type) {
    case "BUDGET_ALERT":
      accentColor = "#f59e0b"; // Amber
      icon = "⚠️";
      break;
    case "GOAL_REACHED":
      accentColor = "#10b981"; // Emerald lighter
      icon = "🏆";
      break;
    case "RECURRING_DEDUCTED":
      accentColor = "#3b82f6"; // Blue
      icon = "🔄";
      break;
    case "LIMIT_WARNING":
      accentColor = "#f43f5e"; // Rose
      icon = "🛑";
      break;
  }

  return (
    <Html>
      <Head />
      <Preview>{title}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={{ ...heading, color: accentColor }}>
            Mizani {icon}
          </Heading>
          <Section style={section}>
            <Text style={greeting}>Hello {name},</Text>
            
            <div style={{ padding: "24px", backgroundColor: `${accentColor}15`, borderRadius: "16px", marginBottom: "24px", border: `1px solid ${accentColor}30` }}>
               <Text style={{ ...alertTitle, color: accentColor }}>{title}</Text>
               <Text style={text}>{message}</Text>
            </div>

            <Text style={text}>
               We are notifying you so you can maintain the equilibrium of your financial framework.
            </Text>

            <Button style={{ ...button, backgroundColor: accentColor }} href={actionUrl}>
              Open Your Sanctuary
            </Button>
            
          </Section>
          <Section style={footer}>
            <Text style={footerText}>Automated alert generated by your Mizani instances.</Text>
            <Text style={footerText}>© {new Date().getFullYear()} Mizani Financial Framework</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

// ─── Styles ──────────────────────────────────────────────────────────────────

const main: React.CSSProperties = {
  backgroundColor: "#f7f9ff",
  fontFamily:
    'Manrope, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, sans-serif',
};

const container: React.CSSProperties = {
  backgroundColor: "#ffffff",
  margin: "40px auto",
  padding: "56px 40px",
  maxWidth: "560px",
  borderRadius: "24px",
  boxShadow: "0 8px 32px -2px rgba(24, 28, 32, 0.05)",
};

const heading: React.CSSProperties = {
  fontSize: "28px",
  fontWeight: "800",
  textAlign: "center" as const,
  margin: "0 0 40px",
  letterSpacing: "-0.02em",
};

const greeting: React.CSSProperties = {
  fontSize: "20px",
  fontWeight: "700",
  color: "#181c20",
  marginBottom: "16px",
};

const alertTitle: React.CSSProperties = {
  fontSize: "18px",
  fontWeight: "800",
  marginBottom: "8px",
  marginTop: "0",
};

const section: React.CSSProperties = {
  padding: "0",
};

const text: React.CSSProperties = {
  fontSize: "16px",
  lineHeight: "1.6",
  color: "#181c20",
  margin: "0",
};

const button: React.CSSProperties = {
  borderRadius: "16px",
  color: "#ffffff",
  fontSize: "16px",
  fontWeight: "700",
  textDecoration: "none",
  textAlign: "center" as const,
  display: "block",
  padding: "16px 32px",
  margin: "32px 0",
};

const footer: React.CSSProperties = {
  marginTop: "40px",
  paddingTop: "32px",
  borderTop: "1px solid #f1f4fa",
};

const footerText: React.CSSProperties = {
  fontSize: "12px",
  lineHeight: "1.5",
  color: "#94a3b8",
  textAlign: "center" as const,
  margin: "4px 0",
};
